Fix building doc for Finch.
Without this change I get these error when running 'make install' from
doc/reference/finch/:

  DOC   Preparing build
  DOC   Scanning header files
  DOC   Introspecting gobjects
/usr/bin/ld: .libs/finch-scan.o: undefined reference to symbol 'gnt_button_get_type'
/home/dude/code/prefix/lib/libgnt.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Linking of scanner failed:
make: *** [scan-build.stamp] Error 1